# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-13 20:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='f_fim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fim_group', models.CharField(max_length=100)),
                ('fim_owner', models.CharField(max_length=50)),
                ('fim_requestor', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 1, 13, 15, 45, 52, 55000))),
            ],
        ),
    ]
