# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-13 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='verification_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 1, 13, 18, 30, 0, 602000))),
                ('utilized', models.BooleanField(default=False)),
                ('utilized_at', models.DateTimeField(blank=True)),
            ],
        ),
    ]
