# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-13 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(blank=True)),
                ('message', models.TextField()),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2019, 1, 13, 15, 34, 25, 133000))),
            ],
        ),
    ]
