# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-13 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_log',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 15, 39, 5, 116000)),
        ),
    ]
