# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-13 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='f_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_from', models.CharField(max_length=50)),
                ('e_to', models.CharField(max_length=50)),
                ('e_cc', models.CharField(max_length=50)),
                ('e_bcc', models.CharField(max_length=50)),
                ('e_subject', models.CharField(max_length=50)),
                ('e_body', models.TextField()),
                ('e_sent_time', models.DateTimeField(default=datetime.datetime(2019, 1, 13, 15, 39, 5, 111000))),
            ],
        ),
    ]
