# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-13 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faux_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='f_email',
            options={'ordering': ['-e_sent_time'], 'verbose_name': 'eMail', 'verbose_name_plural': 'eMails'},
        ),
        migrations.AlterField(
            model_name='f_email',
            name='e_bcc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='f_email',
            name='e_cc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='f_email',
            name='e_sent_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 18, 8, 14, 366000)),
        ),
        migrations.AlterField(
            model_name='f_email',
            name='e_subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
